### ISSUE TITLE
ETH → DFC: Tx Error upon first select `Review tx` (WBTC → dBTC)

### ISSUE THREAD

**Issue by izzycsy** [BirthdayResearch/quantum#691]
```
Ver: 1.1.1
Network: MainNet
Flow: ETH → DFC 
Description: Tx Error upon first select `Review tx` (WBTC → dBTC)
```

**Actual:**
Tried sending `0.0001` WBTC from ETH → DFC > ` Review transaction` > `error:` Transaction Error <string> > at **Transaction Error** pop-up modal, select `Try again` > redirects to MetaMask extension 

**Expected:**
Tried sending `0.0001` WBTC from ETH → DFC > `Review transaction` > redirects to **Review Transaction** pop-up modal > select `Confirm transfer on wallet` > redirects to MetaMask extension > `Confirm` 

**To reproduce:**
1. Select Source Network: Ethereum
2. Input `0.0001` wBTC > select `Review transaction` > `error:` redirects to Transaction Error pop-up modal
3. at **Transaction Error** pop-up modal, select `Try again` > redirects to MetaMask extension 

https://user-images.githubusercontent.com/65014479/223425746-4f66a2a0-50b8-4bca-9759-fa2e7d3ad292.mov

![230307 Quantum ETH   DFC - WBTC   dBTC - tx error on first try2](https://user-images.githubusercontent.com/65014479/223425782-889e324e-5741-43b9-bcd0-d7527660a040.png)

**Comment by lykalabrada** [comment]
Hi @izzycsy, can you help check if you're still seeing the same issue? I saw you've already successfully bridged WBTC, I wanted to confirm if this is a "first-time" user issue or not. Thanks!

**Comment by lykalabrada** [comment]
Reopening issue for QA to verify.

**Comment by izzycsy** [comment]
Issue resolved v.1.5.0
