### ISSUE TITLE
Transaction failed from ETH to Defichain

### ISSUE THREAD

**Issue by Bullpit11** [BirthdayResearch/quantum#746]
Hello, I just made a transaction of 99 EUROC from ETH to DFI chain. After the 65 confirmations it broke off and "Transaction failed" was displayed. Retry multiple times failed. During the analysis, "api.quantumbridge.app/ethereum/allocateDFCFund:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)" and "{status: 400,...}" is displayed in the browser's console window.
error
:
"There is a problem in allocating fund: 400 - BadRequest (/v0/mainnet/rawtx/send): AccountToAccountTx: amount 9.99929700 is less than 99.00000000 (code 16)"
status
:
400" displayed.

My wallet address ( ETH ) is: 0x76851a6f9146cc9ec57A0e18b20120F5cb9B3bEe

My DFI address is: df1q0f0j2sejs88q54g6qhve7k884awulh9x3rfj40

Hash: 0x055e6936a251359904e6d62bb58fa1e04539685f0beeeda8abcdbfbcd2bd7168

Best regards,
Peter

(translated from German into English with google)

**Comment by thedoublejay** [comment]
Hi @Bullpit11, I think transaction has been completed now. https://defiscan.live/transactions/8d2d7c97bf0742707edb08d44f0cd6edbc0f533ecf39f489f93433fb4b6098f1
