### ISSUE TITLE
Quantum Bridge Transaction failed - EUROC missing

### ISSUE THREAD

**Issue by AlexT010101** [BirthdayResearch/quantum#748]
#### What happened: Transfer EUROC from Metamask via Quantum Bridge to Defichain. First Transaction is good. Etherscan: 0x76375da5387912e0c5f82bc96ee132284460e448db191040b5f5a98954d6f602 

Second Transaction with another EUROC failed. Text on Website Quantum Bridge: "Transaction failed
We encountered an error while processing your transaction. Please try again after a few minutes." 
Etherscan: 0x4adc4acfcf7ce87a6014ff9047d543482162c8d90646939926ce5b746a46461f
EUROC are nether on Metamask, nor on Defichain Light wallet: df1qg55menhkc0qv265yxpjave6m906p2e730rddsf
Several Times refreshed, and tried to send again on Website Quantum Bridge. Metamask reconnected - still the same error message on the Website. 

![2023-03-13 (1)](https://user-images.githubusercontent.com/110345626/224747763-cc808390-fd33-4cf7-9890-27dd090d9973.png)

**Comment by AlexT010101** [comment]
Ethereum side of the Bridge was empty. Cap way too low. Not informed at all.

**Comment by mikhail-zlochevskyi** [comment]
@AlexT010101 thank you for your inquiry, we are already working on displaying available liquidity on UI. Please be patient, it 
 is expected in the upcoming releases. Thank you.
