### ISSUE TITLE
ETH to Defichain: EUROC Bridge Tx failed, ~1918 EUROC

### ISSUE THREAD

**Issue by Defianer** [BirthdayResearch/quantum#752]
Hi,

after 65 confirmations the Bridge UI shows "Tx failed, please try again later". However, it's been > 340 confirmations now and not working.

"Inspect" shows Error Code 500 and when opening the link , https://api.quantumbridge.app/ethereum/allocateDFCFund then I get:
"{"statusCode":404,"message":"Cannot GET /ethereum/allocateDFCFund","error":"Not Found"}"

ERC20 Address: 0xffb4ebfc14c9df2784ff483629e706e8b49596d1
Defichain Address: df1qs7uza0nxz9pq9tuwrh7dmslfkqs63aey7yeghv
Amount: 1918.49749 EUROC
Etherscan Tx: 0x79ae86dca326180a24144907d28ea8c985f758212a104ce9ec40839a5a7d1803

**Comment by thedoublejay** [comment]
Hi @Defianer, we're checking on this

**Comment by Defianer** [comment]
After clearing cookies and reloading the page, I was able to use the "restore Tx" function now, which has worked. Resolving.
