### ISSUE TITLE
cannot claim USDT on etherium

### ISSUE THREAD

**Issue by Monika-lala** [BirthdayResearch/quantum#759]

**Comment by thedoublejay** [comment]
Hi, there's a very limited on USDT (ETH) right now that's why it's not working.

**Comment by Monika-lala** [comment]
I tried to bridge 300 dUSDT to USDT. Sent them to df1q9p4s589396qjv4n48eq75gjdfvpkm6x84kgxhc. transaction was confirmed. tried to claim 300 USDT on the ERC 20 side. Confirmend transaction in METAMASK. The message " this will take e few seconds" but it stayed for houres. tried to speed up the transaction. that failed. in the end the Transaction appers as failed. 

https://etherscan.io/tx/0x9c2820ac3310b370f0fb7d8f29761d423fa28f48c163642ae05aaab4f8cbf9ea

how to reclaim dUSDT? How to claim USDT?
>

**Comment by Monika-lala** [comment]
> Hi, there's a very limited on USDT (ETH) right now that's why it's not working.

thanks, but now? can I get dUSDT back? How can I claim USDT?

**Comment by RoMi1981** [comment]
> Hi, there's a very limited on USDT (ETH) right now that's why it's not working.

@thedoublejay please recheck provided information from Monika. She asks how to get lost usdt funds after facing issues while bridging.

Please reopen this issue until it is solved.

Thanks

**Comment by thedoublejay** [comment]
Hi @RoMi1981 @Monika-lala will get back to you on this

**Comment by thedoublejay** [comment]
Funds has been refunded, please check your wallet thanks
