### ISSUE TITLE
"Unable to process transaction" error when transferring any tokens from DeFiChain to Ethereum

### ISSUE THREAD

**Issue by dknugo** [BirthdayResearch/quantum#760]
When trying to transfer any token from DeFiChain to Ethereum the following error is displayed under "Review transaction" button: "Unable to process transaction.Please try again later". "Review transaction" button is grayed.
<img width="488" alt="error" src="https://user-images.githubusercontent.com/18755758/225743661-71689ba8-373a-4a8a-96fd-13d7c6870d6a.png">

**Comment by thedoublejay** [comment]
Hi @dknugo, this one is expected. We're working on displaying the liquidity on the page itself. But right now, there are no liquidity for USDC on ETH side.
