### ISSUE TITLE
`DFI` - Support for Quantum

### ISSUE THREAD

**Issue by thedoublejay** [BirthdayResearch/quantum#761]
#### Why do we need this?

We want to enable DFI support for Quantum. For this, we will support UTXO (not token to token) because DFI on exchanges, other apps only support UTXO. Good thing is on light wallet and most apps in general, we support DFI UTXO.

This is the SC for DFI token (ERC-20) - https://etherscan.io/token/0x8fc8f8269ebca376d046ce292dc7eac40c8d358a

#### What would you like to be added:

- [ ] add DFI token in `SUPPORTED_EVM_TOKENS` .and `SUPPORTED_DFC_TOKENS ` in .env file  along with testnet DFI eth token address
- [ ] update `apps/server/src/AppConfig.ts` to support DFI 
- [ ] update `apps/server/src/defichain/model/VerifyDto.ts` to support DFI 
- [ ] add mapping for DFI token in `apps/server/src/utils/TokensUtils.ts`
- [ ] add DFI SC address on `apps/web/src/config/index.ts`
- [ ] add DFI support in bridge form her `apps/web/src/layouts/contexts/NetworkContext.tsx`
- [ ] update types `apps/web/src/types.ts`
- [ ]  add DFI testnet token address here `packages/smartcontracts/src/scripts/goerliMintApprove.ts`
- [ ] update interrogation test `apps/server/test-i9n/testing/TestingModule.ts` , `apps/server/test-i9n/testing/SettingsController.i9n.ts`, `apps/server/test-i9n/testing/BridgeContractFixture.ts`, `apps/server/test-i9n/defichain/verify.i9n.ts`
- [ ] Update TODO, I think there's a comment that says something about smart contract
- [ ] Add a warning when bridging DFi that we need to send UTXO instead of token.

**Comment by kyleleow** [comment]
Do we want to place `DFI` as the first option? 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/40191153/226233270-e3f489a0-75ea-45a2-b965-81504d8ff14e.png">

**Comment by kyleleow** [comment]
Do we have the testnet DFI token address? If no, how can we create one?

**Comment by thedoublejay** [comment]
@kyleleow Yep let's place it as first option. For DFI testnet, you can coordinate with @Abhishekkochar since they created the mock tokens on Goerli. @fullstackninja864 is familiar with the process

**Comment by Abhishekkochar** [comment]
@kyleleow we created a mock dfi token while ago when testing the LM on mainnet. We can probably use that one. I will let you know the address soon. Need to look for it.
